---
- name: DotCube Provisioning
  hosts: localhost
  connection: local
  vars:
    called_from: "main"

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Detect wsl
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: Normalize run tags
      ansible.builtin.set_fact:
        normalized_run_tags: "{{ ansible_run_tags is string | ternary([ansible_run_tags], ansible_run_tags | default([])) }}"
      tags:
        - always

    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ (normalized_run_tags | length > 0 and 'all' not in normalized_run_tags) | ternary(normalized_run_tags, default_roles | difference(exclude_roles | default([]))) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
